version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  linux:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  windows:
    executor: win/vs2019
    working_directory: ~/repo
    steps:
      - checkout
      - run: Set-ExecutionPolicy RemoteSigned -scope CurrentUser
      - run:
          name: "Install Package Manager"
          command: iwr -useb get.scoop.sh | iex
      - run:
          name: "Install Node"
          command: scoop install nodejs
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - linux
      - windows
